import test from 'node:test';
import assert from 'node:assert/strict';
import {apply,normalizeRoom} from '../lib/radio/model.ts';
const room=()=>({id:'ROOM',name:'Test',members:[{id:'h',name:'Host',role:'host',canRequest:true},{id:'l',name:'Listener',role:'listener',canRequest:true}],requests:[],queue:[],current:null,startedAt:null,offset:0,playing:false,requestsOpen:true,volume:.8,ducked:false,crossfadeSeconds:4,revision:0});
const track={id:'1234567890abcdef1234567890abcdef',title:'Song',artist:'Artist',url:'/api/tracks/1234567890abcdef1234567890abcdef/audio',duration:120,source:'upload'};
test('listeners can request but cannot approve, sequence or control the room',()=>{const r=apply(room(),'l',{type:'request',track});assert.equal(r.requests.length,1);assert.equal(r.queue.length,0);for(const type of ['approve','enqueue','move','remove','next','pause','resume','permission','requestsOpen','volume','duck','crossfade'])assert.throws(()=>apply(r,'l',{type,key:r.requests[0].key}),/Only the host/);});
test('host approval, sequencing, start and pause preserve the programme',()=>{let r=apply(room(),'l',{type:'request',track});r=apply(r,'h',{type:'approve',key:r.requests[0].key});r=apply(r,'h',{type:'next'},10000);assert.equal(r.current.id,track.id);assert.equal(r.queue.length,0);r=apply(r,'h',{type:'pause'},15000);assert.equal(r.offset,5);assert.equal(r.playing,false);r=apply(r,'h',{type:'resume'},20000);assert.equal(r.offset,5);assert.equal(r.startedAt,20000);});
test('closed requests and member permissions are enforced server-side',()=>{let r=apply(room(),'h',{type:'permission',member:'l',value:false});assert.throws(()=>apply(r,'l',{type:'request',track}),/closed/);r=apply(room(),'h',{type:'requestsOpen',value:false});assert.throws(()=>apply(r,'l',{type:'request',track}),/closed/);assert.throws(()=>apply(room(),'outsider',{type:'request',track}),/Join/);});
test('malformed song metadata and duplicate requests are rejected',()=>{assert.throws(()=>apply(room(),'l',{type:'request',track:{...track,title:{unsafe:true}}}));const r=apply(room(),'l',{type:'request',track});assert.throws(()=>apply(r,'l',{type:'request',track}),/already/);assert.equal(room().requests.length,0);});
test('host mixer settings are bounded and listeners cannot change them',()=>{let r=apply(room(),'h',{type:'volume',value:.35});r=apply(r,'h',{type:'duck',value:true});r=apply(r,'h',{type:'crossfade',seconds:7});assert.equal(r.volume,.35);assert.equal(r.ducked,true);assert.equal(r.crossfadeSeconds,7);assert.throws(()=>apply(r,'h',{type:'volume',value:1.1}),/between 0 and 100/);assert.throws(()=>apply(r,'h',{type:'crossfade',seconds:13}),/between 0 and 12/);assert.throws(()=>apply(r,'l',{type:'duck',value:false}),/Only the host/);});
test('hosts can add an uploaded track directly to the queue',()=>{const r=apply(room(),'h',{type:'enqueue',track});assert.equal(r.queue.length,1);assert.equal(r.queue[0].id,track.id);assert.equal(r.queue[0].requestedBy,'h');});
test('legacy provider tracks are removed when stored rooms are normalized',()=>{const legacy={...track,id:'123',url:'https://music.apple.com/song/123',source:undefined,key:'old',requestedBy:'h',requestedName:'Host'};const r=normalizeRoom({...room(),current:legacy,queue:[legacy],requests:[legacy],playing:true,startedAt:100});assert.equal(r.current,null);assert.deepEqual(r.queue,[]);assert.deepEqual(r.requests,[]);assert.equal(r.playing,false);});

// A freshly queued room has songs but no `current`. Only "next" promotes the
// first entry, so this is the contract the Play button depends on to start a
// stopped programme; "resume" on an empty deck is a hard error, not a no-op.
test('a queued but stopped room starts by promoting the first song',()=>{let r=apply(room(),'h',{type:'enqueue',track});assert.equal(r.queue.length,1);assert.equal(r.current,null);assert.equal(r.playing,false);assert.throws(()=>apply(r,'h',{type:'resume'}),/Choose the next song first/);r=apply(r,'h',{type:'next'},10000);assert.equal(r.current.id,track.id);assert.equal(r.playing,true);assert.equal(r.startedAt,10000);assert.equal(r.queue.length,0);});
